# General settings
blockExoticSubdeps: true
confirmModulesPurge: false
engineStrict: true
minimumReleaseAge: 7200 # 5 days
strictDepBuilds: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 129600 # 90 days
verifyDepsBeforeRun: error

allowBuilds:
  "core-js": false
  "esbuild@0.28.1": true

overrides:
  esbuild: 0.28.1

# Pacquet disabled until pnpm 12
#configDependencies:
#  '@pnpm/pacquet': 0.11.12

# Workspace

packages:
  - packages/*
  - demos/*
