name: Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Test coverage for package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [ core, with-reselect ]

    steps:
      - uses: actions/checkout@v3

      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run package tests
        run: |
          cd packages/${{ matrix.package-name }}
          pnpm run test:coverage

      - name: Report package test coverage to coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ github.token }}
          path-to-lcov: packages/${{ matrix.package-name }}/coverage/lcov.info
          base-path: packages/${{ matrix.package-name }}
          git-branch: x-cov-${{ matrix.package-name }}
