name: Coverage

on:
  push:
    branches:
      - branch-coverage

jobs:
  test-core:
    name: Test coverage for @dynamic-selectors/core
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ env.NVMRC }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Run tests
        run: |
          cd packages/core
          yarn run test:coverage

      - name: Temp debug
        run: |
          cat packages/core/coverage-local/lcov.info

      - name: Report package test coverage to coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ github.token }}
          path-to-lcov: packages/core/coverage-local/lcov.info
          base-path: packages/core
          git-branch: x-cov-core

  test-with-reselect:
    name: Test coverage for @dynamic-selectors/with-reselect
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ env.NVMRC }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Run tests
        run: |
          cd packages/with-reselect
          yarn run test:coverage

      - name: Temp debug
        run: |
          cat packages/with-reselect/coverage-local/lcov.info

      - name: Report package test coverage to coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ github.token }}
          path-to-lcov: packages/with-reselect/coverage-local/lcov.info
          base-path: packages/with-reselect
          git-branch: x-cov-with-reselect
