name: Per-Package Test Coverage

on:
  push:
    branches:
      - main

jobs:
  package-test-coverage:
    name: Package test coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name: [ core, with-reselect ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run package tests
        run: |
          cd packages/${{ matrix.package-name }}
          pnpm run test:coverage

      - name: Report package test coverage to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          path-to-lcov: packages/${{ matrix.package-name }}/coverage/lcov.info
          base-path: packages/${{ matrix.package-name }}
          git-branch: x-cov-${{ matrix.package-name }}
